#!/bin/bash

docker run --platform linux/amd64 -v "$(pwd)":/apps --rm alpine/bundle:2.7.0 \
/bin/bash -c "gem install bundler:2.4.2 \
&& bundle config --local path 'vendor/bundle' \
&& bundle install \
&& (bundle exec rubocop; \
bundle exec rspec)"